<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <xs:element name="carrito" type="CarritoResponse"/>
  <xs:element name="agregarProducto" type="ProductoCarritoDTO"/>
  <xs:element name="cambiarCantidad" type="CambiarCantidadRequest"/>

  <xs:complexType name="CarritoResponse">
    <xs:sequence>
      <xs:element name="items" type="CarritoItems"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CarritoItems">
    <xs:sequence>
      <xs:element name="item" type="ProductoCarritoDTO" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ProductoCarritoDTO">
    <xs:sequence>
      <xs:element name="idProducto" type="xs:string"/>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="cantidad">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="precioUnitario" type="xs:decimal"/>
      <xs:element name="subtotal" type="xs:decimal"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CambiarCantidadRequest">
    <xs:sequence>
      <xs:element name="cantidad">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
