<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

  <xs:element name="productos" type="ProductosResponse"/>

  <xs:complexType name="ProductosResponse">
    <xs:sequence>
      <xs:element name="producto" type="ProductoOutput" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ProductoOutput">
    <xs:sequence>
      <xs:element name="idProducto" type="xs:string"/>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="precio" type="xs:decimal"/>
      <xs:element name="stock" type="xs:integer"/>
      <xs:element name="urlImagen" type="xs:string" minOccurs="0"/>
      <xs:element name="SKU" type="xs:string"/>
      <xs:element name="codigoBarras" type="xs:string" minOccurs="0"/>
      <xs:element name="categoria" type="CategoriaOutput"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="CategoriaOutput">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
